
export const campingMockdata = [
    {
        addr1: "경상북도 칠곡군 가산면 응추리 ",
        addr2: "183",
        allar: 28000,
        animalCmgCl: "불가능",
        autoSiteCo: 48,
        bizrno: "403-39-61259",
        brazierCl: "개별",
        caravAcmpnyAt: "N",
        caravSiteCo: 0,
        clturEventAt: "N",
        contentId: 3429,
        createdtime: "2021-11-23 20:41:43           ",
        doNm: "경상북도",
        eqpmnLendCl: "텐트,릴선,화로대,난방기구,식기",
        exprnProgrmAt: "N",
        extshrCo: 25,
        facltDivNm: "민간",
        facltNm: "한티별빛아래관광농원 야영장 ",
        featureNm: "카페",
        fireSensorCo: 0,
        firstImageUrl: "https://gocamping.or.kr/upload/camp/3429/thumb/thumb_720_7798D931eCFr52PoJOTNrEdo.jpg",
        frprvtSandCo: 4,
        frprvtWrppCo: 0,
        glampSiteCo: 0,
        gnrlSiteCo: 0,
        homepage: "http://cafe.daum.net/hantistar-camp",
        induty: "일반야영장",
        indvdlCaravSiteCo: 0,
        insrncAt: "N",
        intro: "한티 별빛아래 오토캠핑장은 경북 칠곡군 가산면에 자리 잡았다. 칠곡군청을 기점으로 33㎞가량 떨어졌으며, 자동차에 몸을 싣고 호국로, 남원로, 79번 지방도를 차례로 달리면 닿는다. 도착까지 걸리는 시간은 50분 안팎이다. 이곳은 ‘높은 고개’란 의미를 지닌 한티재 인근에 위치했다. 고지대인 덕택에 한여름 낮 시간에는 다른 지역에 비해 무덥지 않다. 해가 진 저녁에는 닭살이 살짝 돋는 선선함을 느낄 정도다. 게다가 캠핑장에서 발 아래로 내려다보는 풍경은 감탄사를 자아낼 정도로 멋지다. 캠핑장에는 48면의 자동차 야영장을 마련했다. 바닥 형태는 파쇄석이며, 사이트 크기는 가로 6m 세로 9m다. 개인 트레일러는 물론 카라반 동반 입장이 가능하다. 주말 운영을 원칙으로 사계절 내내 문을 연다.  캠핑장 인근에 치산관광지, 팔공산도립공원, 블루데이식물원 등이 있어 연계관광이 용이하다. 팔공산 주변에 여러 음식점도 성업 중이라 먹을거리를 찾아 나서기에 부담이 없다.",
        lctCl: "산",
        lineIntro: "발 아래로 내려다보는 풍경이 일품",
        manageNmpr: 2,
        manageSttus: "운영",
        mangeDivNm: "직영",
        mapX: 128.6142847,
        mapY: 36.0345423,
        modifiedtime: "2021-11-23 20:41:43           ",
        operDeCl: "주말",
        operPdCl: "봄,여름,가을,겨울",
        posblFcltyCl: "산책로",
        prmisnDe: "2015-08-11",
        resveCl: "온라인실시간예약",
        resveUrl: "http://r6.camperstory.com/?1789",
        sbrsCl: "전기,무선인터넷,장작판매,온수,물놀이장,산책로,운동시설",
        sigunguNm: "칠곡군",
        siteBottomCl1: 0,
        siteBottomCl2: 48,
        siteBottomCl3: 0,
        siteBottomCl4: 0,
        siteBottomCl5: 0,
        siteMg1Co: 48,
        siteMg1Vrticl: 9,
        siteMg1Width: 6,
        siteMg2Co: 0,
        siteMg2Vrticl: 0,
        siteMg2Width: 0,
        siteMg3Co: 0,
        siteMg3Vrticl: 0,
        siteMg3Width: 0,
        sitedStnc: 3,
        swrmCo: 2,
        tel: "054-972-8032",
        themaEnvrnCl: "봄꽃여행,여름물놀이,가을단풍명소,겨울눈꽃명소",
        toiletCo: 4,
        trlerAcmpnyAt: "Y",
        wtrplCo: 2,
        zipcode: 718911,
    },
    {
        addr1: "경상북도 칠곡군 가산면 응추리 ",
        addr2: "183",
        allar: 28000,
        animalCmgCl: "불가능",
        autoSiteCo: 48,
        bizrno: "403-39-61259",
        brazierCl: "개별",
        caravAcmpnyAt: "N",
        caravSiteCo: 0,
        clturEventAt: "N",
        contentId: 3429,
        createdtime: "2021-11-23 20:41:43           ",
        doNm: "경상북도",
        eqpmnLendCl: "텐트,릴선,화로대,난방기구,식기",
        exprnProgrmAt: "N",
        extshrCo: 25,
        facltDivNm: "민간",
        facltNm: "한티별빛아래관광농원 야영장 ",
        featureNm: "카페",
        fireSensorCo: 0,
        firstImageUrl: "https://gocamping.or.kr/upload/camp/3429/thumb/thumb_720_7798D931eCFr52PoJOTNrEdo.jpg",
        frprvtSandCo: 4,
        frprvtWrppCo: 0,
        glampSiteCo: 0,
        gnrlSiteCo: 0,
        homepage: "http://cafe.daum.net/hantistar-camp",
        induty: "일반야영장",
        indvdlCaravSiteCo: 0,
        insrncAt: "N",
        intro: "한티 별빛아래 오토캠핑장은 경북 칠곡군 가산면에 자리 잡았다. 칠곡군청을 기점으로 33㎞가량 떨어졌으며, 자동차에 몸을 싣고 호국로, 남원로, 79번 지방도를 차례로 달리면 닿는다. 도착까지 걸리는 시간은 50분 안팎이다. 이곳은 ‘높은 고개’란 의미를 지닌 한티재 인근에 위치했다. 고지대인 덕택에 한여름 낮 시간에는 다른 지역에 비해 무덥지 않다. 해가 진 저녁에는 닭살이 살짝 돋는 선선함을 느낄 정도다. 게다가 캠핑장에서 발 아래로 내려다보는 풍경은 감탄사를 자아낼 정도로 멋지다. 캠핑장에는 48면의 자동차 야영장을 마련했다. 바닥 형태는 파쇄석이며, 사이트 크기는 가로 6m 세로 9m다. 개인 트레일러는 물론 카라반 동반 입장이 가능하다. 주말 운영을 원칙으로 사계절 내내 문을 연다.  캠핑장 인근에 치산관광지, 팔공산도립공원, 블루데이식물원 등이 있어 연계관광이 용이하다. 팔공산 주변에 여러 음식점도 성업 중이라 먹을거리를 찾아 나서기에 부담이 없다.",
        lctCl: "산",
        lineIntro: "발 아래로 내려다보는 풍경이 일품",
        manageNmpr: 2,
        manageSttus: "운영",
        mangeDivNm: "직영",
        mapX: 128.6142847,
        mapY: 36.0345423,
        modifiedtime: "2021-11-23 20:41:43           ",
        operDeCl: "주말",
        operPdCl: "봄,여름,가을,겨울",
        posblFcltyCl: "산책로",
        prmisnDe: "2015-08-11",
        resveCl: "온라인실시간예약",
        resveUrl: "http://r6.camperstory.com/?1789",
        sbrsCl: "전기,무선인터넷,장작판매,온수,물놀이장,산책로,운동시설",
        sigunguNm: "칠곡군",
        siteBottomCl1: 0,
        siteBottomCl2: 48,
        siteBottomCl3: 0,
        siteBottomCl4: 0,
        siteBottomCl5: 0,
        siteMg1Co: 48,
        siteMg1Vrticl: 9,
        siteMg1Width: 6,
        siteMg2Co: 0,
        siteMg2Vrticl: 0,
        siteMg2Width: 0,
        siteMg3Co: 0,
        siteMg3Vrticl: 0,
        siteMg3Width: 0,
        sitedStnc: 3,
        swrmCo: 2,
        tel: "054-972-8032",
        themaEnvrnCl: "봄꽃여행,여름물놀이,가을단풍명소,겨울눈꽃명소",
        toiletCo: 4,
        trlerAcmpnyAt: "Y",
        wtrplCo: 2,
        zipcode: 718911,
    },
    {
        addr1: "경상북도 칠곡군 가산면 응추리 ",
        addr2: "183",
        allar: 28000,
        animalCmgCl: "불가능",
        autoSiteCo: 48,
        bizrno: "403-39-61259",
        brazierCl: "개별",
        caravAcmpnyAt: "N",
        caravSiteCo: 0,
        clturEventAt: "N",
        contentId: 3429,
        createdtime: "2021-11-23 20:41:43           ",
        doNm: "경상북도",
        eqpmnLendCl: "텐트,릴선,화로대,난방기구,식기",
        exprnProgrmAt: "N",
        extshrCo: 25,
        facltDivNm: "민간",
        facltNm: "한티별빛아래관광농원 야영장 ",
        featureNm: "카페",
        fireSensorCo: 0,
        firstImageUrl: "https://gocamping.or.kr/upload/camp/3429/thumb/thumb_720_7798D931eCFr52PoJOTNrEdo.jpg",
        frprvtSandCo: 4,
        frprvtWrppCo: 0,
        glampSiteCo: 0,
        gnrlSiteCo: 0,
        homepage: "http://cafe.daum.net/hantistar-camp",
        induty: "일반야영장",
        indvdlCaravSiteCo: 0,
        insrncAt: "N",
        intro: "한티 별빛아래 오토캠핑장은 경북 칠곡군 가산면에 자리 잡았다. 칠곡군청을 기점으로 33㎞가량 떨어졌으며, 자동차에 몸을 싣고 호국로, 남원로, 79번 지방도를 차례로 달리면 닿는다. 도착까지 걸리는 시간은 50분 안팎이다. 이곳은 ‘높은 고개’란 의미를 지닌 한티재 인근에 위치했다. 고지대인 덕택에 한여름 낮 시간에는 다른 지역에 비해 무덥지 않다. 해가 진 저녁에는 닭살이 살짝 돋는 선선함을 느낄 정도다. 게다가 캠핑장에서 발 아래로 내려다보는 풍경은 감탄사를 자아낼 정도로 멋지다. 캠핑장에는 48면의 자동차 야영장을 마련했다. 바닥 형태는 파쇄석이며, 사이트 크기는 가로 6m 세로 9m다. 개인 트레일러는 물론 카라반 동반 입장이 가능하다. 주말 운영을 원칙으로 사계절 내내 문을 연다.  캠핑장 인근에 치산관광지, 팔공산도립공원, 블루데이식물원 등이 있어 연계관광이 용이하다. 팔공산 주변에 여러 음식점도 성업 중이라 먹을거리를 찾아 나서기에 부담이 없다.",
        lctCl: "산",
        lineIntro: "발 아래로 내려다보는 풍경이 일품",
        manageNmpr: 2,
        manageSttus: "운영",
        mangeDivNm: "직영",
        mapX: 128.6142847,
        mapY: 36.0345423,
        modifiedtime: "2021-11-23 20:41:43           ",
        operDeCl: "주말",
        operPdCl: "봄,여름,가을,겨울",
        posblFcltyCl: "산책로",
        prmisnDe: "2015-08-11",
        resveCl: "온라인실시간예약",
        resveUrl: "http://r6.camperstory.com/?1789",
        sbrsCl: "전기,무선인터넷,장작판매,온수,물놀이장,산책로,운동시설",
        sigunguNm: "칠곡군",
        siteBottomCl1: 0,
        siteBottomCl2: 48,
        siteBottomCl3: 0,
        siteBottomCl4: 0,
        siteBottomCl5: 0,
        siteMg1Co: 48,
        siteMg1Vrticl: 9,
        siteMg1Width: 6,
        siteMg2Co: 0,
        siteMg2Vrticl: 0,
        siteMg2Width: 0,
        siteMg3Co: 0,
        siteMg3Vrticl: 0,
        siteMg3Width: 0,
        sitedStnc: 3,
        swrmCo: 2,
        tel: "054-972-8032",
        themaEnvrnCl: "봄꽃여행,여름물놀이,가을단풍명소,겨울눈꽃명소",
        toiletCo: 4,
        trlerAcmpnyAt: "Y",
        wtrplCo: 2,
        zipcode: 718911,
    },
    
]